### PR TITLE
Added Station filtering

### PR DESCRIPTION
**Pull request by stanfear**
Added a new textfield to enter the filter (filters are kept throughout
saves)
Added an on_tick event every 60 ticks to react to player chages in
filter box
Used a single function to update GUI (updateStationsGUI)
Changed various styles

### CODE REVIEW

**Comment by simwir** [comment]
There seems to be a bug in your code. See the [forum](https://forums.factorio.com/viewtopic.php?f=92&t=23776&p=152412#p152412) post

**Comment by stanfear** [comment]
ok, I'll check that

**Comment by stanfear** [comment]
ok, I think it is fixed (I wasn't removing the tag to force the update of the GUI... which made it go back to page one every secound)

**Comment by simwir** [comment]
Thought the problem was something like that.

**Pull request merged**
