### PR TITLE
Switch GUI elements to use numbered indices instead of stop names

### PR DESCRIPTION
**Pull request by kaufman-bryce**
Corrects issue #31

Created purely through the web interface, so it's not diffing correctly. Changes are on lines 143,144, and 281. Causes GUI buttons in stop list to use numbered indices for names, and use the captions to set shuttle destinations.

### CODE REVIEW

**Comment by simwir** [comment]
What exactly did you change, because the "files changed" view does not help at all...

**Comment by kaufman-bryce** [comment]
Sorry about that, I'm not sure what I did wrong. First time forking for a pull request like this.
143 - `(event.element.name == station.backer_name)` becomes `(event.element.caption == station.backer_name)`
144 - `station = event.element.name` becomes `station = event.element.caption`
281 Old - `player.gui.left.shuttleTrain.flow.add{type = "button", name = name, caption = name, style = "st-station-button"}`
281 New - `player.gui.left.shuttleTrain.flow.add{type = "button", name = stationsAdded+1, caption = name, style = "st-station-button"}`

**Comment by simwir** [comment]
Ohh i see. My guess is the problem is line endings or something, making it look like you changed every line. I get your solution but do not have time to test or compile a new version as i'm on holiday, will look into it later.

**Comment by simwir** [comment]
Due to the fact that it thinks you have changed every line it won't let me merge, so i've added the changes my self.

**Pull request closed without merging**
